// Generated by https://quicktype.io

export interface WeeklyTrackChart {
    track:   Track[];
    "@attr": WeeklyTrackChartAttr;
}

export interface WeeklyTrackChartAttr {
    user: string;
    from: string;
    to:   string;
}

export interface Track {
    artist:    Artist;
    name:      string;
    mbid:      string;
    playcount: string;
    image:     Image[];
    url:       string;
    "@attr":   TrackAttr;
}

export interface TrackAttr {
    rank: string;
}

export interface Artist {
    "#text": string;
    mbid:    string;
}

export interface Image {
    "#text": string;
    size:    Size;
}

export enum Size {
    Large = "large",
    Medium = "medium",
    Small = "small",
}
